function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Logic_Calc"};
	this.sidHashMap["Logic_Calc"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "Logic_Calc:10"};
	this.sidHashMap["Logic_Calc:10"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/In2"] = {sid: "Logic_Calc:11"};
	this.sidHashMap["Logic_Calc:11"] = {rtwname: "<Root>/In2"};
	this.rtwnameHashMap["<Root>/Bitwise Operator"] = {sid: "Logic_Calc:1"};
	this.sidHashMap["Logic_Calc:1"] = {rtwname: "<Root>/Bitwise Operator"};
	this.rtwnameHashMap["<Root>/Bitwise Operator1"] = {sid: "Logic_Calc:2"};
	this.sidHashMap["Logic_Calc:2"] = {rtwname: "<Root>/Bitwise Operator1"};
	this.rtwnameHashMap["<Root>/Bitwise Operator2"] = {sid: "Logic_Calc:3"};
	this.sidHashMap["Logic_Calc:3"] = {rtwname: "<Root>/Bitwise Operator2"};
	this.rtwnameHashMap["<Root>/Bitwise Operator3"] = {sid: "Logic_Calc:4"};
	this.sidHashMap["Logic_Calc:4"] = {rtwname: "<Root>/Bitwise Operator3"};
	this.rtwnameHashMap["<Root>/Bitwise Operator4"] = {sid: "Logic_Calc:9"};
	this.sidHashMap["Logic_Calc:9"] = {rtwname: "<Root>/Bitwise Operator4"};
	this.rtwnameHashMap["<Root>/Bitwise Operator6"] = {sid: "Logic_Calc:7"};
	this.sidHashMap["Logic_Calc:7"] = {rtwname: "<Root>/Bitwise Operator6"};
	this.rtwnameHashMap["<Root>/Bitwise Operator7"] = {sid: "Logic_Calc:8"};
	this.sidHashMap["Logic_Calc:8"] = {rtwname: "<Root>/Bitwise Operator7"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "Logic_Calc:12"};
	this.sidHashMap["Logic_Calc:12"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "Logic_Calc:13"};
	this.sidHashMap["Logic_Calc:13"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "Logic_Calc:14"};
	this.sidHashMap["Logic_Calc:14"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "Logic_Calc:15"};
	this.sidHashMap["Logic_Calc:15"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<Root>/Output4"] = {sid: "Logic_Calc:16"};
	this.sidHashMap["Logic_Calc:16"] = {rtwname: "<Root>/Output4"};
	this.rtwnameHashMap["<Root>/Output5"] = {sid: "Logic_Calc:17"};
	this.sidHashMap["Logic_Calc:17"] = {rtwname: "<Root>/Output5"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
